version: '2'
services:
#### MYSQL DATABASE
  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: always
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - db_data:/data
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

#### POSTGRES DATABASE
  postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - db_data:/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

