version: '2.1'
services:

  web:
    links: [ app ]
    ports: [ "${SERVICE_PORT}:80" ]

  app:
    links: [ db, cache ]
    volumes: [ "app_data:/data" ]

  db:
    volumes: [ "db_data:/data" ]

  cache:
    volumes: [ "cache_data:/data" ]

volumes:
  app_data: {}
  db_data: {}
  cache_data: {}
