version: '2.1'
services:

  web:
    extends:
      service: nginx
      file: web-engines.yml

  app:
    extends:
      service: php
      file: service-engines.yml

  db:
    extends:
      service: cassandra
      file: database-engines.yml

  initdb:
    extends:
      service: cassandra
      file: database-engines.yml
    depends_on: [ db ]
    command: /docker-entrypoint-initdb.d/cassandra
    restart: on-failure

  cache:
     extends:                     
       service: redis
       file: cache-engines.yml

