version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: web.docker
        ports:
            - "8081:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: app.docker