version: '2.1'
services:

  web:
    links: [ app ]
    ports: [ "${SERVICE_PORT}:80" ]

  app:
    links: [ postgres, cassandra, cache ]
    volumes: [ "app_data:/data" ]

  postgres:
    volumes: [ "postgres_data:/data" ]

  cassandra:
    volumes: [ "cassandra_data:/data" ]

  cache:
    volumes: [ "cache_data:/data" ]

volumes:
  app_data: {}
  cassandra_data: {}
  postgres_data: {}
  cache_data: {}
