version: '2.1'
services:

  web:
    links: [ app ]
    ports: [ "${SERVICE_PORT}:80" ]

  app:
    links: [ db, cache ]
    volumes: [ "app_data:/data" ]

  db:
    volumes: [ "db_data:/data" ]

  cache:
    volumes: [ "cache_data:/data" ]

volumes:
  app_data: {}
  db_data: {}
  cache_data: {}

networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.32.0.0/24
        gateway: 172.32.0.254
