version: '2.1'
services:
#### WEB
  web:
    extends:
      file: web-engines.yml
      service: ${WEB_ENGINE}
    links:
      - app
    ports:
      - "${SERVICE_PORT}:80"

#### APPLICATION
  app:
    image: ${APP_NAME}:${APP_VERSION}-${APP_STAGE}
    extends:
      file: service-engines.yml
      service: ${SERVICE_ENGINE}
    volumes:
      - ./app:/app
    links:
      - db
      - cache
    environment:
      - APP_STAGE
      - APP_NAME
      - APP_VERSION

#  app:
#    image: ${APP_NAME}:${APP_VERSION}
#    build:
#      context: ./app
#      args:
#        pkg: ${APP_APT_PACKAGES}
#        ext: ${APP_PHP_EXTENSIONS}
#    restart: always
#    links:
#      - db
#      - cache
#    volumes:
#      - ./app:/app
#      - ./conf/php.ini:/usr/local/etc/php/php.ini
#    environment:
#      - APP_STAGE
#      - APP_NAME
#      - APP_VERSION

#### DATABASE
  db:
    extends:
      file: database-engines.yml
      service: ${DATABASE_ENGINE}
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - db_data:/data

#### CACHE
  cache:
    extends:
      file: cache-engines.yml
      service: ${CACHE_ENGINE}
    volumes:
      - cache_data:/data

volumes:
  db_data:
  cache_data:

