version: '2.1'
services:
#### WEB
  web:
    extends:
      file: web-engines.yml
      service: ${WEB_ENGINE}
    restart: always
    links:
      - app
    ports:
      - "${WEB_PORT}:80"

#### PHP APPLICATION
  app:
    image: ${APP_NAME}:${APP_VERSION}
    build:
      context: ./
      args:
        pkg: ${APP_APT_PACKAGES}
        ext: ${APP_PHP_EXTENSIONS}
    restart: always
    links:
      - db
      - cache
    volumes:
      - ./app:/app
      - ./conf/php.ini:/usr/local/etc/php/php.ini
    environment:
      - APP_STAGE
      - APP_NAME
      - APP_VERSION

#### DATABASE
  db:
    extends:
      file: database-engines.yml
      service: ${DATABASE_ENGINE}
    restart: always
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - db_data:/data

#### CACHE
  cache:
    extends:
      file: cache-engines.yml
      service: ${CACHE_ENGINE}
    restart: always
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - cache_data:/data

volumes:
  db_data:
  cache_data:

