version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.web
    ports:
      - "8088:80"
    links:
      - app

  app:
    build:
      context: ./
      dockerfile: Dockerfile.app

