version: '2.1'
services:

  nginx:
    image: nginx:${NGINX_VERSION}
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/vhosts.conf:/etc/nginx/conf.d/default.conf
